name: Run Postman Tests and Publish Report

on:
  push:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Newman
        run: |
          npm install -g newman
          npm install newman-reporter-htmlextra

      - name: Run local server
        run: npm run tern-on-api &

      - name: Run Postman Tests
        run: |
          mkdir -p docs
          newman run store.collection.json -e env.json \
            -r htmlextra
            --reporter-htmlextra-export docs/index.html
        continue-on-error: true
